"""empty message

Revision ID: 97d71ccd951a
Revises: 
Create Date: 2024-03-24 19:58:45.637769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d71ccd951a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('transcription', sa.String(length=156), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word'),
    schema='words'
    )
    op.create_table('translation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('part_of_speech', sa.Enum('verb', 'prep', 'noun', 'adj', 'pronoun', 'adverb', 'conjuction', 'interjection', name='partofspeech'), nullable=False),
    sa.Column('wordname', sa.String(), nullable=False),
    sa.Column('language', sa.Enum('Russian', name='language'), nullable=False),
    sa.ForeignKeyConstraint(['wordname'], ['words.words.word'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='words'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation', schema='words')
    op.drop_table('words', schema='words')
    # ### end Alembic commands ###
